# Ciência de Dados

# Big Data Real-Time Analytics com Python e Spark

# Capítulo 3

Dados obtidos do Portal Brasileiro de Dados Abertos:
http://dados.gov.br/dataset/cidades-digitais

O projeto Cidades Digitais foi planejado para modernizar a gestão e ampliar o acesso ao serviço público, bem como promover o desenvolvimento dos municípios brasileiros através da tecnologia.

# Group By e Reshape

In [1]:
import numpy as np
import pandas as pd

In [2]:
cidadesDigitais = pd.read_csv('data/cidades_digitais.csv', sep = ';', encoding = 'latin-1')

In [3]:
cidadesDigitais.head()

,UF,CIDADE,IBGE,POPULAÇÃO,VALOR_TOTAL_PREVISTO,STATUS,PONTOS_ATENDIDOS,VALOR_INVESTIDO
0,AC,Tarauacá,1200609,38819,"484.547,53",Sem Previsão,8,0
1,AL,Delmiro Gouveia,2702405,51997,"1.169.381,70",Sem Previsão,43,0
2,AL,Estrela de Alagoas,2702553,18306,"527.206,83",Sem Previsão,39,0
3,AM,Autazes,1300300,37033,"1.171.151,92",Sem Previsão,51,0
4,AM,Benjamin Constant,1300607,39484,"844.586,48",Sem Previsão,12,0

In [4]:
cidadesDigitais.count()

UF                      338
CIDADE                  338
IBGE                    338
POPULAÇÃO               338
VALOR_TOTAL_PREVISTO    338
STATUS                  338
PONTOS_ATENDIDOS        338
VALOR_INVESTIDO         338
dtype: int64

In [5]:
del cidadesDigitais['IBGE']

In [6]:
# Aplicando Group By
cidadesUF_1 = cidadesDigitais.groupby('UF')

In [7]:
type(cidadesUF_1)

pandas.core.groupby.generic.DataFrameGroupBy

In [9]:
cidadesUF_1.head()

,UF,CIDADE,POPULAÇÃO,VALOR_TOTAL_PREVISTO,STATUS,PONTOS_ATENDIDOS,VALOR_INVESTIDO
0,AC,Tarauacá,38819,"484.547,53",Sem Previsão,8,0
1,AL,Delmiro Gouveia,51997,"1.169.381,70",Sem Previsão,43,0
2,AL,Estrela de Alagoas,18306,"527.206,83",Sem Previsão,39,0
3,AM,Autazes,37033,"1.171.151,92",Sem Previsão,51,0
4,AM,Benjamin Constant,39484,"844.586,48",Sem Previsão,12,0
...,...,...,...,...,...,...,...
303,SP,Cachoeira Paulista,32294,"935.119,68",Sem Previsão,27,0
334,TO,Paraíso do Tocantins,49076,"1.872.693,90",Sem Previsão,49,0
335,TO,Ponte Alta do Bom Jesus,4649,"251.266,44",Sem Previsão,9,"23.969,90"
336,TO,Porto Nacional,52182,"1.101.168,76",Sem Previsão,61,0
337,TO,São Miguel do Tocantins,11597,"592.549,70",Sem Previsão,20,0

In [10]:
cidadesUF_1.groups

{'AC': Int64Index([0], dtype='int64'),
 'AL': Int64Index([1, 2], dtype='int64'),
 'AM': Int64Index([3, 4, 5, 6, 7, 8, 9, 10, 11], dtype='int64'),
 'AP': Int64Index([12, 13, 14, 15, 16, 17], dtype='int64'),
 'BA': Int64Index([18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
             35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
            dtype='int64'),
 'CE': Int64Index([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
             68, 69, 70, 71, 72, 73, 74, 75, 76],
            dtype='int64'),
 'DF': Int64Index([77], dtype='int64'),
 'ES': Int64Index([78, 79, 80, 81], dtype='int64'),
 'GO': Int64Index([82, 83, 84, 85, 86, 87, 88, 89, 90, 91], dtype='int64'),
 'MA': Int64Index([ 92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
             105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117],
            dtype='int64'),
 'MG': Int64Index([118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
             131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
             144, 145],
            dtype='int64'),
 'MS': Int64Index([146, 147, 148], dtype='int64'),
 'MT': Int64Index([149, 150, 151, 152], dtype='int64'),
 'PA': Int64Index([153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
             166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176],
            dtype='int64'),
 'PB': Int64Index([177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189,
             190, 191, 192, 193, 194],
            dtype='int64'),
 'PE': Int64Index([195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
             208, 209, 210],
            dtype='int64'),
 'PI': Int64Index([211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223,
             224, 225, 226, 227, 228],
            dtype='int64'),
 'PR': Int64Index([229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241,
             242, 243, 244, 245],
            dtype='int64'),
 'RJ': Int64Index([246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258,
             259, 260],
            dtype='int64'),
 'RN': Int64Index([261, 262, 263, 264, 265, 266, 267, 268, 269], dtype='int64'),
 'RO': Int64Index([270, 271], dtype='int64'),
 'RR': Int64Index([272], dtype='int64'),
 'RS': Int64Index([273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
             286, 287, 288],
            dtype='int64'),
 'SC': Int64Index([289, 290, 291, 292, 293, 294], dtype='int64'),
 'SE': Int64Index([295, 296, 297, 298], dtype='int64'),
 'SP': Int64Index([299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
             312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
             325, 326, 327, 328, 329, 330, 331, 332, 333],
            dtype='int64'),
 'TO': Int64Index([334, 335, 336, 337], dtype='int64')}

In [11]:
# Número de grupos
len(cidadesUF_1.groups)

27

In [12]:
ordenaUF = cidadesUF_1.size()

In [13]:
# Ordena os grupos por ordem decrescente
ordenaUF.sort_values(ascending = False)

UF
SP    35
BA    33
MG    28
MA    26
CE    26
PA    24
PI    18
PB    18
PR    17
PE    16
RS    16
RJ    15
GO    10
RN     9
AM     9
AP     6
SC     6
ES     4
TO     4
MT     4
SE     4
MS     3
RO     2
AL     2
DF     1
RR     1
AC     1
dtype: int64

In [14]:
cidadesUF_2 = cidadesDigitais.groupby(['UF','STATUS'])

In [15]:
total = cidadesUF_2.size()
total.sort_values(ascending = False)
total

UF  STATUS
AC  Sem Previsão     1
AL  Sem Previsão     2
AM  Concluída        3
    Sem Previsão     6
AP  Concluída        1
    Sem Previsão     5
BA  Concluída        9
    Sem Previsão    24
CE  Concluída       11
    Sem Previsão    15
DF  Concluída        1
ES  Sem Previsão     4
GO  Sem Previsão    10
MA  Concluída        1
    Sem Previsão    25
MG  Concluída        2
    Em andamento     1
    Sem Previsão    25
MS  Sem Previsão     3
MT  Sem Previsão     4
PA  Concluída        9
    Sem Previsão    15
PB  Concluída        6
    Em andamento     3
    Sem Previsão     9
PE  Concluída        1
    Sem Previsão    15
PI  Concluída        3
    Sem Previsão    15
PR  Concluída        7
    Em andamento     1
    Sem Previsão     9
RJ  Concluída        1
    Em andamento     2
    Sem Previsão    12
RN  Concluída        1
    Sem Previsão     8
RO  Sem Previsão     2
RR  Sem Previsão     1
RS  Concluída        4
    Em andamento     2
    Sem Previsão    10
SC  Concluída        1
    Sem Previsão     5
SE  Sem Previsão     4
SP  Concluída        8
    Em andamento     2
    Sem Previsão    25
TO  Sem Previsão     4
dtype: int64

In [16]:
cidadesDigitais.head()

,UF,CIDADE,POPULAÇÃO,VALOR_TOTAL_PREVISTO,STATUS,PONTOS_ATENDIDOS,VALOR_INVESTIDO
0,AC,Tarauacá,38819,"484.547,53",Sem Previsão,8,0
1,AL,Delmiro Gouveia,51997,"1.169.381,70",Sem Previsão,43,0
2,AL,Estrela de Alagoas,18306,"527.206,83",Sem Previsão,39,0
3,AM,Autazes,37033,"1.171.151,92",Sem Previsão,51,0
4,AM,Benjamin Constant,39484,"844.586,48",Sem Previsão,12,0

In [17]:
cidadesUF_3 = cidadesDigitais.set_index('STATUS')

In [18]:
# Aplicando Group By
cidadesUF_3 = cidadesUF_3.groupby(level = 'STATUS')

In [19]:
cidadesUF_3.head()

,UF,CIDADE,POPULAÇÃO,VALOR_TOTAL_PREVISTO,PONTOS_ATENDIDOS,VALOR_INVESTIDO
STATUS,,,,,,
Sem Previsão,AC,Tarauacá,38819,"484.547,53",8,0
Sem Previsão,AL,Delmiro Gouveia,51997,"1.169.381,70",43,0
Sem Previsão,AL,Estrela de Alagoas,18306,"527.206,83",39,0
Sem Previsão,AM,Autazes,37033,"1.171.151,92",51,0
Sem Previsão,AM,Benjamin Constant,39484,"844.586,48",12,0
Concluída,AM,Coari,83078,"814.954,75",27,0
Concluída,AM,Manacapuru,94175,"892.096,87",31,"763.009,30"
Concluída,AM,Manaquiri,28413,"636.682,15",21,0
Concluída,AP,Serra do Navio,4938,"590.073,15",21,"495.899,00"
Concluída,BA,Guanambi,85797,"533.416,18",15,"441.985,58"
Em andamento,MG,Nepomuceno,26897,"650.576,00",27,0
Em andamento,PB,Cabaceiras,5449,"355.867,86",15,0
Em andamento,PB,Esperança,32785,"643.482,51",23,0
Em andamento,PB,Itaporanga,24499,"649.011,44",23,0
Em andamento,PR,Bandeirantes,32639,"279.409,70",7,0

In [20]:
cidadesUF_4 = cidadesDigitais.set_index(['STATUS', 'UF'])

In [21]:
cidadesUF_4

                                  CIDADE  POPULAÇÃO VALOR_TOTAL_PREVISTO  \
STATUS       UF
Sem Previsão AC                 Tarauacá      38819           484.547,53
             AL          Delmiro Gouveia      51997         1.169.381,70
             AL       Estrela de Alagoas      18306           527.206,83
             AM                  Autazes      37033         1.171.151,92
             AM        Benjamin Constant      39484           844.586,48
...                                  ...        ...                  ...
             SP     Vargem Grande do Sul      41807         1.525.640,54
             TO     Paraíso do Tocantins      49076         1.872.693,90
             TO  Ponte Alta do Bom Jesus       4649           251.266,44
             TO           Porto Nacional      52182         1.101.168,76
             TO  São Miguel do Tocantins      11597           592.549,70

                 PONTOS_ATENDIDOS VALOR_INVESTIDO
STATUS       UF
Sem Previsão AC                 8               0
             AL                43               0
             AL                39               0
             AM                51               0
             AM                12               0
...                           ...             ...
             SP                47               0
             TO                49               0
             TO                 9       23.969,90
             TO                61               0
             TO                20               0

[338 rows x 5 columns]

In [22]:
cidadesUF_4 = cidadesDigitais.set_index(['UF', 'STATUS'])

In [23]:
cidadesUF_4 = cidadesUF_4.groupby(level = ['UF', 'STATUS'])

In [24]:
cidadesUF_4.sum()

                 POPULAÇÃO  PONTOS_ATENDIDOS
UF STATUS
AC Sem Previsão      38819                 8
AL Sem Previsão      70303                82
AM Concluída        205666                79
   Sem Previsão     204136               167
AP Concluída          4938                21
   Sem Previsão     107938                81
BA Concluída       1171174               155
   Sem Previsão     532445               559
CE Concluída        658927               218
   Sem Previsão     427514               370
DF Concluída         32148                15
ES Sem Previsão     122164                94
GO Sem Previsão     166045               168
MA Concluída        174267                13
   Sem Previsão     571514               566
MG Concluída         18579                16
   Em andamento      26897                27
   Sem Previsão     465789               533
MS Sem Previsão     118431                94
MT Sem Previsão      77241                97
PA Concluída        620301               189
   Sem Previsão     470578               435
PB Concluída        127879                95
   Em andamento      62733                61
   Sem Previsão     111071               185
PE Concluída         37317                14
   Sem Previsão     342519               297
PI Concluída         37987                45
   Sem Previsão     187556               213
PR Concluída        418078               134
   Em andamento      32639                 7
   Sem Previsão     284252               247
RJ Concluída         13626                11
   Em andamento     167465                35
   Sem Previsão     413049               312
RN Concluída          6218                13
   Sem Previsão      77814               145
RO Sem Previsão      84470                39
RR Sem Previsão      27288                21
RS Concluída        107356                73
   Em andamento      40954                30
   Sem Previsão     300041               265
SC Concluída         29008                18
   Sem Previsão     187416                90
SE Sem Previsão     187455               107
SP Concluída        235299               173
   Em andamento      62857                37
   Sem Previsão     898779               810
TO Sem Previsão     117504               139

In [25]:
cidadesUF_4.aggregate(np.sum)

                 POPULAÇÃO  PONTOS_ATENDIDOS
UF STATUS
AC Sem Previsão      38819                 8
AL Sem Previsão      70303                82
AM Concluída        205666                79
   Sem Previsão     204136               167
AP Concluída          4938                21
   Sem Previsão     107938                81
BA Concluída       1171174               155
   Sem Previsão     532445               559
CE Concluída        658927               218
   Sem Previsão     427514               370
DF Concluída         32148                15
ES Sem Previsão     122164                94
GO Sem Previsão     166045               168
MA Concluída        174267                13
   Sem Previsão     571514               566
MG Concluída         18579                16
   Em andamento      26897                27
   Sem Previsão     465789               533
MS Sem Previsão     118431                94
MT Sem Previsão      77241                97
PA Concluída        620301               189
   Sem Previsão     470578               435
PB Concluída        127879                95
   Em andamento      62733                61
   Sem Previsão     111071               185
PE Concluída         37317                14
   Sem Previsão     342519               297
PI Concluída         37987                45
   Sem Previsão     187556               213
PR Concluída        418078               134
   Em andamento      32639                 7
   Sem Previsão     284252               247
RJ Concluída         13626                11
   Em andamento     167465                35
   Sem Previsão     413049               312
RN Concluída          6218                13
   Sem Previsão      77814               145
RO Sem Previsão      84470                39
RR Sem Previsão      27288                21
RS Concluída        107356                73
   Em andamento      40954                30
   Sem Previsão     300041               265
SC Concluída         29008                18
   Sem Previsão     187416                90
SE Sem Previsão     187455               107
SP Concluída        235299               173
   Em andamento      62857                37
   Sem Previsão     898779               810
TO Sem Previsão     117504               139

In [ ]:
cidadesUF_4.aggregate([np.sum, np.mean, np.size])

In [ ]:
cidadesUF_5 = cidadesDigitais.set_index([ 'STATUS', 'CIDADE', 'VALOR_TOTAL_PREVISTO', 'VALOR_INVESTIDO', 'POPULAÇÃO', 'PONTOS_ATENDIDOS'])

In [ ]:
cidadesUF_5 = cidadesUF_5.groupby(level = ['STATUS', 'VALOR_TOTAL_PREVISTO', 'VALOR_INVESTIDO'])

In [ ]:
cidadesDigitais.head(3)

In [ ]:
cidadesUF_5.sum()

# Fim